import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/Footer";
import Providers from "./Provider";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-mywhite`}>
        <div className="max-w-[90%] mx-auto">
          <Providers>
        <Navbar/>
        {children}
       <Footer/>
       </Providers>
        </div>
        </body>
    </html>
  );
}
